### ISSUE TITLE
Verify/update displayed category-data

### ISSUE THREAD

**Issue by tklein1801** [BudgetBuddyDE/Webapp#25]
## Parent
- [x] #19 

## Acceptance criteria
- ~Display data as a bar-chart~
  - ~Number of transactions per category~
  - ~Number of subscriptions per category~
- [x] Display data as a pie-chart
  - [x] Earnings by category
  - [x] Spendings by category

**Comment by tklein1801** [comment]
**TODO**

- [ ]  Create RPC's for calculation the chart-values
