### ISSUE TITLE
Verify/update displayed payment-method data

### ISSUE THREAD

**Issue by tklein1801** [BudgetBuddyDE/Webapp#26]
## Parent
- [x] #19 

## Acceptance criteria
- [x] Display data as a bar-chart
  - [x] Number of transactions per payment-method
  - [x] Number of subscriptions per payment-method
- [x] Display data as a pie-chart
  - [x] Earnings by payment-method
  - [x] Spendings by payment-method

**Comment by tklein1801** [comment]
**TODO**: Create RPC's for calculation the chart-values
